version: '3'

services:
  streamer:
    container_name: 'streamer'
    build:
      context: ./streamer
      dockerfile: ./dockerfile
    restart: always
    ports:
      - 5454:5454
    volumes:
      - ./data/streamer:/usr/src/app/bin
  recorder:
    container_name: 'recorder'
    build:
      context: ./recorder
      dockerfile: ./dockerfile
    restart: always
    ports:
      - 5000:5000
    volumes:
      - ./data/recorder:/usr/src/app/bin
  postgres:
    container_name: 'postgres'
    image: 'postgres:13'
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: farmdata
  mosquitto:
    container_name: 'mosquitto'
    image: 'eclipse-mosquitto:2.0.10'
    restart: always
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./data/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    depends_on:
      - postgres
  grafana:
    container_name: grafana
    image: grafana/grafana:7.1.5
    restart: always
    ports:
      - 3002:3000
    volumes:
      - ./data/grafana:/var/lib/grafana:rw
    depends_on:
      - postgres
    user: "472"