version: '3'

services:
  postgres:
    container_name: 'postgres'
    image: 'postgres:13'
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: farmdata
  grafana:
    container_name: grafana
    image: grafana/grafana:7.1.5
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana:rw
    depends_on:
      - postgres
      - recorder