FROM python:3.8.5

WORKDIR /usr/src/app

COPY requirements.txt ./

RUN apt-get update -y

RUN apt-get install libgl1-mesa-glx cmake -y

RUN pip3 install --upgrade pip

RUN pip3 install -r requirements.txt

COPY . .

EXPOSE 5000

WORKDIR /usr/src/app/src

CMD ["python3", "main.py"]