FROM python:3.8.5

COPY . /usr/src

WORKDIR /usr/src

RUN apt-get update -y && \
    apt-get install libpq-dev gcc libgl1-mesa-glx cmake curl -y && \
    pip3 install --upgrade pip && \
    pip3 install -r requirements.txt

EXPOSE 5000

CMD ["python3", "src/main.py"]