FROM python:3.8.5

COPY . /usr/src

RUN apt-get update -y && \
    apt-get install libgl1-mesa-glx cmake -y \
    pip3 install --upgrade pip \
    pip3 install -r requirements.txt

EXPOSE 5000

WORKDIR /usr/src

CMD ["python3", "src/main.py"]